server.port=8080
# Database Config
config.database-config.host=jdbc:postgresql://localhost:5432/spring_security_pkce
config.database-config.username=postgres
config.database-config.password=
# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Jwt KeyStore
jwt.keystore.jks-location=keystore/spring-angular.jks
jwt.keystore.key-alias=spring-angular
jwt.keystore.password=tqu8zA1jtrFV
# Security Config
config.security.issuer=http://localhost:8080
config.security.redirect-uris=http://localhost:4200/callback
config.security.cors=http://localhost:4200
config.security.authorization-endpoint=/oauth2/authorize
config.security.token-endpoint=/oauth2/token
config.context-path.client-path=http://localhost:4200
