spring.application.name=spring-authorization-pkce
spring.profiles.active=dev
spring.threads.virtual.enabled=true
# Exclude null fields from JSON
spring.jackson.default-property-inclusion=non_null
#JPA configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect